### ISSUE TITLE
在cflow里使用截图重命名有没有办法自动改为时间戳？

### ISSUE THREAD

**Issue by brmysss** [Vespa314/cflow#1]
<img width="687" alt="image" src="https://github.com/user-attachments/assets/4d68be9e-af0f-4a51-82f7-3fe72fbafce4">

<img width="527" alt="image" src="https://github.com/user-attachments/assets/38157dc9-bcfd-4dc3-8d0d-9afd2456e5de">

如图所示，我粘贴图片的时候，图片默认名为：image.png，有没有办法将这个默认名改为时间戳或自定义？
我不知道去哪里该代码...

**Comment by Vespa314** [comment]
https://github.com/Vespa314/cflow/blob/main/web/src/components/ImageRenameDialag.tsx#L16  这一行哈

**Comment by brmysss** [comment]
> https://github.com/Vespa314/cflow/blob/main/web/src/components/ImageRenameDialag.tsx#L16 这一行哈

感谢！问题已解决
